check:
  - overlays-build
overlays_dir: overlays
overlays:
  - name: download-dataset
    build:
      base-image: "quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.28.0"
      build-stratergy: Source
      registry: quay.io
      registry-org: jakang
      registry-project: elyra-aidevsecops-dataset
      registry-secret: jakang-pusher-secret

  - name: training
    build:
      base-image: "quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.28.0"
      build-stratergy: Source
      registry: quay.io
      registry-org: jakang
      registry-project: elyra-aidevsecops-training
      registry-secret: jakang-pusher-secret

  - name: experiment
    build:
      base-image: "quay.io/thoth-station/s2i-elyra-custom-notebook:v0.4.1"
      build-source-script: "image:///opt/app-root/builder"
      custom-tag: latest
      build-stratergy: Source
      registry: quay.io
      registry-org: jakang
      registry-project: elyra-aidevsecops-experiment
      registry-secret: jakang-pusher-secret

  - name: inference
    build:
      base-image: "quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.28.0"
      build-stratergy: Source
      registry: quay.io
      registry-org: jakang
      registry-project: elyra-aidevsecops-tutorial
      registry-secret: jakang-pusher-secret
    deploy:
      project-org: "thoth-station"
      project-name: "elyra-aidevsecops-tutorial"
      image-name: "elyra-aidevsecops-tutorial"
      overlay-contextpath: "manifests/overlays/inference/imagestreamtag.yaml"
    gather:
      overlay-name: test-model
      name: gather_deployment_metrics_using_tensorflow

  - name: nm-download
    build:
      base-image: "quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.28.0"
      build-stratergy: Source
      registry: quay.io
      registry-org: jakang
      registry-project: neural-magic-download
      registry-secret: jakang-pusher-secret

  - name: pytorch-training
    build:
      base-image: "quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.28.0"
      build-stratergy: Source
      registry: quay.io
      registry-org: jakang
      registry-project: pytorch-training
      registry-secret: jakang-pusher-secret

  - name: nm-convert-onnx
    build:
      base-image: "quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.28.0"
      custom-tag: latest
      build-stratergy: Source
      registry: quay.io
      registry-org: jakang
      registry-project: neural-magic-convert-onnx
      registry-secret: jakang-pusher-secret

  - name: nm-sparseml
    build:
      base-image: "quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.28.0"
      custom-tag: latest
      build-stratergy: Source
      registry: quay.io
      registry-org: jakang
      registry-project: neural-magic-sparseml
      registry-secret: jakang-pusher-secret

  - name: nm-inference
    build:
      base-image: "quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.28.0"
      build-stratergy: Source
      registry: quay.io
      registry-org: jakang
      registry-project: neural-magic-deepsparse
      registry-secret: jakang-pusher-secret
    deploy:
      project-org: "thoth-station"
      project-name: "elyra-aidevsecops-tutorial"
      image-name: "neural-magic-deepsparse"
      overlay-contextpath: "manifests/overlays/nm-inference/imagestreamtag.yaml"
    gather:
      overlay-name: test-model
      name: gather_deployment_metrics_using_tensorflow

  - name: pytorch-inference
    build:
      base-image: "quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.28.0"
      build-stratergy: Source
      registry: quay.io
      registry-org: jakang
      registry-project: elyra-aidevsecops-pytorch-inference
      registry-secret: jakang-pusher-secret
    deploy:
      project-org: "thoth-station"
      project-name: "elyra-aidevsecops-tutorial"
      image-name: "elyra-aidevsecops-pytorch-inference"
      overlay-contextpath: "manifests/overlays/pytorch-inference/imagestreamtag.yaml"
    gather:
      overlay-name: test-model
      name: gather_deployment_metrics_using_pytorch
